// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aceDLNMadditivebuild
List aceDLNMadditivebuild(const Eigen::VectorXd R_y, const List R_B_inner_list, const List R_knots_f_list, const Eigen::MatrixXd R_Sw_large, const List R_Sf_list, const Eigen::MatrixXd R_Dw, const Eigen::MatrixXd R_Xrand, const Eigen::MatrixXd R_Xfix, const List R_Zf_list, const Eigen::VectorXd R_Xoffset, const Eigen::VectorXd R_r, const Eigen::MatrixXd R_K, const Eigen::VectorXd R_a, Eigen::VectorXd R_alpha_f, Eigen::VectorXd R_phi, double R_log_theta, Eigen::VectorXd R_log_smoothing_f, Eigen::VectorXd R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing);
RcppExport SEXP _aceDLNMadditive_aceDLNMadditivebuild(SEXP R_ySEXP, SEXP R_B_inner_listSEXP, SEXP R_knots_f_listSEXP, SEXP R_Sw_largeSEXP, SEXP R_Sf_listSEXP, SEXP R_DwSEXP, SEXP R_XrandSEXP, SEXP R_XfixSEXP, SEXP R_Zf_listSEXP, SEXP R_XoffsetSEXP, SEXP R_rSEXP, SEXP R_KSEXP, SEXP R_aSEXP, SEXP R_alpha_fSEXP, SEXP R_phiSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_y(R_ySEXP);
    Rcpp::traits::input_parameter< const List >::type R_B_inner_list(R_B_inner_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_knots_f_list(R_knots_f_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Sw_large(R_Sw_largeSEXP);
    Rcpp::traits::input_parameter< const List >::type R_Sf_list(R_Sf_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Dw(R_DwSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xrand(R_XrandSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xfix(R_XfixSEXP);
    Rcpp::traits::input_parameter< const List >::type R_Zf_list(R_Zf_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_Xoffset(R_XoffsetSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_r(R_rSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_K(R_KSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_a(R_aSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_phi(R_phiSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    rcpp_result_gen = Rcpp::wrap(aceDLNMadditivebuild(R_y, R_B_inner_list, R_knots_f_list, R_Sw_large, R_Sf_list, R_Dw, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_K, R_a, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing));
    return rcpp_result_gen;
END_RCPP
}
// aceDLNMadditiveopt
List aceDLNMadditiveopt(SEXP ptr, SEXP ptrcppad, Eigen::VectorXd R_alpha_f, Eigen::VectorXd R_phi, double R_log_theta, Eigen::VectorXd R_log_smoothing_f, Eigen::VectorXd R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing, bool verbose);
RcppExport SEXP _aceDLNMadditive_aceDLNMadditiveopt(SEXP ptrSEXP, SEXP ptrcppadSEXP, SEXP R_alpha_fSEXP, SEXP R_phiSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrcppad(ptrcppadSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_phi(R_phiSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(aceDLNMadditiveopt(ptr, ptrcppad, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, verbose));
    return rcpp_result_gen;
END_RCPP
}
// aceDLNMadditiveCI
List aceDLNMadditiveCI(SEXP ptr, const int Rci, const int rseed, bool ifeta, bool delta, bool verbose);
RcppExport SEXP _aceDLNMadditive_aceDLNMadditiveCI(SEXP ptrSEXP, SEXP RciSEXP, SEXP rseedSEXP, SEXP ifetaSEXP, SEXP deltaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const int >::type Rci(RciSEXP);
    Rcpp::traits::input_parameter< const int >::type rseed(rseedSEXP);
    Rcpp::traits::input_parameter< bool >::type ifeta(ifetaSEXP);
    Rcpp::traits::input_parameter< bool >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(aceDLNMadditiveCI(ptr, Rci, rseed, ifeta, delta, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ConditionalAICaceDLNMadditive
List ConditionalAICaceDLNMadditive(SEXP ptr);
RcppExport SEXP _aceDLNMadditive_ConditionalAICaceDLNMadditive(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ConditionalAICaceDLNMadditive(ptr));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon1st
Eigen::VectorXd BsplinevecCon1st(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _aceDLNMadditive_BsplinevecCon1st(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon1st(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon2nd
Eigen::VectorXd BsplinevecCon2nd(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _aceDLNMadditive_BsplinevecCon2nd(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon2nd(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// knotindex
int knotindex(double x, Eigen::VectorXd t);
RcppExport SEXP _aceDLNMadditive_knotindex(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(knotindex(x, t));
    return rcpp_result_gen;
END_RCPP
}
// Bspline
double Bspline(double x, int j, Eigen::VectorXd t, int p);
RcppExport SEXP _aceDLNMadditive_Bspline(SEXP xSEXP, SEXP jSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bspline(x, j, t, p));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec
Eigen::VectorXd Bsplinevec(double x, Eigen::VectorXd t, int p);
RcppExport SEXP _aceDLNMadditive_Bsplinevec(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec(x, t, p));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon
Eigen::VectorXd BsplinevecCon(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _aceDLNMadditive_BsplinevecCon(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecConJ
double BsplinevecConJ(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z, int j);
RcppExport SEXP _aceDLNMadditive_BsplinevecConJ(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecConJ(x, t, p, Z, j));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2
Eigen::VectorXd Bsplinevec2(double x, Eigen::VectorXd t, int p);
RcppExport SEXP _aceDLNMadditive_Bsplinevec2(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2(x, t, p));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2Con
Eigen::VectorXd Bsplinevec2Con(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _aceDLNMadditive_Bsplinevec2Con(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2Con(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2ConJ
double Bsplinevec2ConJ(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z, int j);
RcppExport SEXP _aceDLNMadditive_Bsplinevec2ConJ(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2ConJ(x, t, p, Z, j));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecFill
void BsplinevecFill(double x, Eigen::VectorXd t, int p, int col, Eigen::SparseMatrix<double>& Gx);
RcppExport SEXP _aceDLNMadditive_BsplinevecFill(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP colSEXP, SEXP GxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Gx(GxSEXP);
    BsplinevecFill(x, t, p, col, Gx);
    return R_NilValue;
END_RCPP
}
// Bsplinevec2Fill
void Bsplinevec2Fill(double x, Eigen::VectorXd t, int p, int col, Eigen::SparseMatrix<double>& Gx);
RcppExport SEXP _aceDLNMadditive_Bsplinevec2Fill(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP colSEXP, SEXP GxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Gx(GxSEXP);
    Bsplinevec2Fill(x, t, p, col, Gx);
    return R_NilValue;
END_RCPP
}
// Integral
List Integral(Eigen::VectorXd knots_x, Eigen::VectorXd knots_w, int kx, int kw, double maxL, Eigen::MatrixXd Zx, Eigen::MatrixXd Zw, Eigen::VectorXd t, Eigen::VectorXd alphax, bool OnlyAlphaxD);
RcppExport SEXP _aceDLNMadditive_Integral(SEXP knots_xSEXP, SEXP knots_wSEXP, SEXP kxSEXP, SEXP kwSEXP, SEXP maxLSEXP, SEXP ZxSEXP, SEXP ZwSEXP, SEXP tSEXP, SEXP alphaxSEXP, SEXP OnlyAlphaxDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_x(knots_xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_w(knots_wSEXP);
    Rcpp::traits::input_parameter< int >::type kx(kxSEXP);
    Rcpp::traits::input_parameter< int >::type kw(kwSEXP);
    Rcpp::traits::input_parameter< double >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zx(ZxSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zw(ZwSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alphax(alphaxSEXP);
    Rcpp::traits::input_parameter< bool >::type OnlyAlphaxD(OnlyAlphaxDSEXP);
    rcpp_result_gen = Rcpp::wrap(Integral(knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD));
    return rcpp_result_gen;
END_RCPP
}
// deBoor
double deBoor(double x, Eigen::VectorXd t, Eigen::VectorXd beta, int p);
RcppExport SEXP _aceDLNMadditive_deBoor(SEXP xSEXP, SEXP tSEXP, SEXP betaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(deBoor(x, t, beta, p));
    return rcpp_result_gen;
END_RCPP
}
// Integral_interpolate
List Integral_interpolate(Eigen::VectorXd knots_x, Eigen::VectorXd knots_w, int kx, int kw, double maxL, Eigen::MatrixXd Zw, Eigen::VectorXd t, Eigen::VectorXd alphax, bool OnlyAlphaxD);
RcppExport SEXP _aceDLNMadditive_Integral_interpolate(SEXP knots_xSEXP, SEXP knots_wSEXP, SEXP kxSEXP, SEXP kwSEXP, SEXP maxLSEXP, SEXP ZwSEXP, SEXP tSEXP, SEXP alphaxSEXP, SEXP OnlyAlphaxDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_x(knots_xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_w(knots_wSEXP);
    Rcpp::traits::input_parameter< int >::type kx(kxSEXP);
    Rcpp::traits::input_parameter< int >::type kw(kwSEXP);
    Rcpp::traits::input_parameter< double >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zw(ZwSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alphax(alphaxSEXP);
    Rcpp::traits::input_parameter< bool >::type OnlyAlphaxD(OnlyAlphaxDSEXP);
    rcpp_result_gen = Rcpp::wrap(Integral_interpolate(knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD));
    return rcpp_result_gen;
END_RCPP
}
// Interpolate
Eigen::VectorXd Interpolate(Eigen::SparseMatrix<double> X, Eigen::VectorXd y);
RcppExport SEXP _aceDLNMadditive_Interpolate(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Interpolate(X, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aceDLNMadditive_aceDLNMadditivebuild", (DL_FUNC) &_aceDLNMadditive_aceDLNMadditivebuild, 21},
    {"_aceDLNMadditive_aceDLNMadditiveopt", (DL_FUNC) &_aceDLNMadditive_aceDLNMadditiveopt, 11},
    {"_aceDLNMadditive_aceDLNMadditiveCI", (DL_FUNC) &_aceDLNMadditive_aceDLNMadditiveCI, 6},
    {"_aceDLNMadditive_ConditionalAICaceDLNMadditive", (DL_FUNC) &_aceDLNMadditive_ConditionalAICaceDLNMadditive, 1},
    {"_aceDLNMadditive_BsplinevecCon1st", (DL_FUNC) &_aceDLNMadditive_BsplinevecCon1st, 4},
    {"_aceDLNMadditive_BsplinevecCon2nd", (DL_FUNC) &_aceDLNMadditive_BsplinevecCon2nd, 4},
    {"_aceDLNMadditive_knotindex", (DL_FUNC) &_aceDLNMadditive_knotindex, 2},
    {"_aceDLNMadditive_Bspline", (DL_FUNC) &_aceDLNMadditive_Bspline, 4},
    {"_aceDLNMadditive_Bsplinevec", (DL_FUNC) &_aceDLNMadditive_Bsplinevec, 3},
    {"_aceDLNMadditive_BsplinevecCon", (DL_FUNC) &_aceDLNMadditive_BsplinevecCon, 4},
    {"_aceDLNMadditive_BsplinevecConJ", (DL_FUNC) &_aceDLNMadditive_BsplinevecConJ, 5},
    {"_aceDLNMadditive_Bsplinevec2", (DL_FUNC) &_aceDLNMadditive_Bsplinevec2, 3},
    {"_aceDLNMadditive_Bsplinevec2Con", (DL_FUNC) &_aceDLNMadditive_Bsplinevec2Con, 4},
    {"_aceDLNMadditive_Bsplinevec2ConJ", (DL_FUNC) &_aceDLNMadditive_Bsplinevec2ConJ, 5},
    {"_aceDLNMadditive_BsplinevecFill", (DL_FUNC) &_aceDLNMadditive_BsplinevecFill, 5},
    {"_aceDLNMadditive_Bsplinevec2Fill", (DL_FUNC) &_aceDLNMadditive_Bsplinevec2Fill, 5},
    {"_aceDLNMadditive_Integral", (DL_FUNC) &_aceDLNMadditive_Integral, 10},
    {"_aceDLNMadditive_deBoor", (DL_FUNC) &_aceDLNMadditive_deBoor, 4},
    {"_aceDLNMadditive_Integral_interpolate", (DL_FUNC) &_aceDLNMadditive_Integral_interpolate, 9},
    {"_aceDLNMadditive_Interpolate", (DL_FUNC) &_aceDLNMadditive_Interpolate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aceDLNMadditive(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
