# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aceDLNMadditivebuild <- function(R_y, R_B_inner_list, R_knots_f_list, R_Sw_large, R_Sf_list, R_Dw, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_K, R_a, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing) {
    .Call(`_aceDLNMadditive_aceDLNMadditivebuild`, R_y, R_B_inner_list, R_knots_f_list, R_Sw_large, R_Sf_list, R_Dw, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_K, R_a, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing)
}

aceDLNMadditiveopt <- function(ptr, ptrcppad, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, verbose) {
    .Call(`_aceDLNMadditive_aceDLNMadditiveopt`, ptr, ptrcppad, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, verbose)
}

aceDLNMadditiveCI <- function(ptr, Rci, rseed, ifeta, delta, verbose) {
    .Call(`_aceDLNMadditive_aceDLNMadditiveCI`, ptr, Rci, rseed, ifeta, delta, verbose)
}

ConditionalAICaceDLNMadditive <- function(ptr) {
    .Call(`_aceDLNMadditive_ConditionalAICaceDLNMadditive`, ptr)
}

BsplinevecCon1st <- function(x, t, p, Z) {
    .Call(`_aceDLNMadditive_BsplinevecCon1st`, x, t, p, Z)
}

BsplinevecCon2nd <- function(x, t, p, Z) {
    .Call(`_aceDLNMadditive_BsplinevecCon2nd`, x, t, p, Z)
}

knotindex <- function(x, t) {
    .Call(`_aceDLNMadditive_knotindex`, x, t)
}

Bspline <- function(x, j, t, p) {
    .Call(`_aceDLNMadditive_Bspline`, x, j, t, p)
}

Bsplinevec <- function(x, t, p) {
    .Call(`_aceDLNMadditive_Bsplinevec`, x, t, p)
}

BsplinevecCon <- function(x, t, p, Z) {
    .Call(`_aceDLNMadditive_BsplinevecCon`, x, t, p, Z)
}

BsplinevecConJ <- function(x, t, p, Z, j) {
    .Call(`_aceDLNMadditive_BsplinevecConJ`, x, t, p, Z, j)
}

Bsplinevec2 <- function(x, t, p) {
    .Call(`_aceDLNMadditive_Bsplinevec2`, x, t, p)
}

Bsplinevec2Con <- function(x, t, p, Z) {
    .Call(`_aceDLNMadditive_Bsplinevec2Con`, x, t, p, Z)
}

Bsplinevec2ConJ <- function(x, t, p, Z, j) {
    .Call(`_aceDLNMadditive_Bsplinevec2ConJ`, x, t, p, Z, j)
}

BsplinevecFill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_aceDLNMadditive_BsplinevecFill`, x, t, p, col, Gx))
}

Bsplinevec2Fill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_aceDLNMadditive_Bsplinevec2Fill`, x, t, p, col, Gx))
}

Integral <- function(knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_aceDLNMadditive_Integral`, knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD)
}

deBoor <- function(x, t, beta, p) {
    .Call(`_aceDLNMadditive_deBoor`, x, t, beta, p)
}

Integral_interpolate <- function(knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_aceDLNMadditive_Integral_interpolate`, knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD)
}

Interpolate <- function(X, y) {
    .Call(`_aceDLNMadditive_Interpolate`, X, y)
}

